#!/bin/bash
#
# chkconfig: 35 90 12
# description: xdmod-server server
#
# Get function from functions library
. /etc/init.d/functions
# Start the service FOO
start() {
	(/usr/local/bin/xdmod-receiver & echo $! > /var/lock/subsys/xdmod-receiver) 2>&1  | logger -t "xdmod-receiver"  &
	ret=$?

        echo -n $"xdmod-receiver server startup"
	if [ $ret -eq 0 ]
	then
		success
	else
		failure
	fi	
	
        echo
}
# Restart the service FOO
stop() {
	echo -n  $"xdmod-receiver server stop"
        killproc -p /var/lock/subsys/xdmod-receiver
        rm -f /var/lock/subsys/xdmod-receiver
        echo
}
### main logic ###
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status -p /var/lock/subsys/xdmod-receiver xdmod-receiver
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac
exit 0
